include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "test/**/*.mocks.dart"
linter:
  rules:
    avoid_positional_boolean_parameters: false
    avoid_function_literals_in_foreach_calls: false
    unsafe_html: false
    avoid_bool_literals_in_conditional_expressions: false
    implementation_imports: false
    require_trailing_commas: false