include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_positional_boolean_parameters: false
    avoid_function_literals_in_foreach_calls: false
    unsafe_html: false
    avoid_bool_literals_in_conditional_expressions: false