name: hkgalden_flutter
description: hkGalden mobile client.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.6.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  zefyr:
    git:
      url: https://github.com/memspace/zefyr.git
      path: packages/zefyr
      ref: 1.0-dev
  flutter_svg: ^0.19.0
  graphql: ^3.1.0
  redux: ^4.0.0+3
  flutter_redux: ^0.6.0
  webview_flutter: ^1.0.0
  flutter_secure_storage: ^3.3.4
  equatable: ^1.2.5
  flutter_html: ^1.0.2
  date_time_format: ^1.1.0
  universal_html: ^1.2.3
  url_launcher: ^5.7.2
  cached_network_image: ^2.3.2+1
  animations: ^1.1.2
  image_downloader: ^0.20.1
  auto_size_text: ^2.1.0
  shimmer: ^1.1.1
  image_picker: ^0.6.7+11
  backdrop: ^0.4.6
  package_info: ^0.4.3
  transparent_image: ^1.0.0

dependency_overrides:
  cupertino_icons: '1.0.0'
  flutter_svg: '0.19.0'
  webview_flutter: '1.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: NotoSansTC
  #     fonts:
  #       - asset: fonts/NotoSansTC-Thin.otf
  #         weight: 100
  #       - asset: fonts/NotoSansTC-Light.otf
  #         weight: 300
  #       - asset: fonts/NotoSansTC-Regular.otf
  #         weight: 400
  #       - asset: fonts/NotoSansTC-Medium.otf
  #         weight: 500
  #       - asset: fonts/NotoSansTC-Bold.otf
  #         weight: 700
  #       - asset: fonts/NotoSansTC-Black.otf
  #         weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/

flutter_icons:
  ios: true
  image_path: "assets/app-icon.png"
  android: true
  adaptive_icon_background: "assets/app-icon.png"
  adaptive_icon_foreground: "assets/android-adaptive.png"
