name: hkgalden_flutter
description: hkGalden mobile client.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.7.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 
  zefyr: ^1.0.0-dev.1.0
  flutter_svg: 
  graphql: ^3.1.0
  redux: 
  flutter_redux: 
  webview_flutter: 
  flutter_secure_storage: 
  equatable: 
  flutter_html: 
  date_time_format: 
  universal_html: 
  url_launcher: 
  cached_network_image: 
  animations: 
  image_downloader: 
  auto_size_text: 
  shimmer: 
  image_picker: 
  backdrop: 
  package_info: 
  modal_bottom_sheet: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: NotoSansTC
  #     fonts:
  #       - asset: fonts/NotoSansTC-Thin.otf
  #         weight: 100
  #       - asset: fonts/NotoSansTC-Light.otf
  #         weight: 300
  #       - asset: fonts/NotoSansTC-Regular.otf
  #         weight: 400
  #       - asset: fonts/NotoSansTC-Medium.otf
  #         weight: 500
  #       - asset: fonts/NotoSansTC-Bold.otf
  #         weight: 700
  #       - asset: fonts/NotoSansTC-Black.otf
  #         weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/

flutter_icons:
  ios: true
  image_path: "assets/app-icon.png"
  android: true
  adaptive_icon_background: "assets/app-icon.png"
  adaptive_icon_foreground: "assets/android-adaptive.png"
