// Mocks generated by Mockito 5.0.3 from annotations
// in hkgalden_flutter/test/bloc_tests/channel_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:hkgalden_flutter/models/channel.dart' as _i4;
import 'package:hkgalden_flutter/repository/channel_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ChannelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannelRepository extends _i1.Mock implements _i2.ChannelRepository {
  MockChannelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Channel>?> getChannels() =>
      (super.noSuchMethod(Invocation.method(#getChannels, []),
              returnValue: Future.value(<_i4.Channel>[]))
          as _i3.Future<List<_i4.Channel>?>);
}
