// Mocks generated by Mockito 5.4.6 from annotations
// in hkgalden_flutter/test/bloc_tests/channel_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hkgalden_flutter/models/channel.dart' as _i4;
import 'package:hkgalden_flutter/repository/channel_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChannelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannelRepository extends _i1.Mock implements _i2.ChannelRepository {
  MockChannelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Channel>?> getChannels() => (super.noSuchMethod(
        Invocation.method(
          #getChannels,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Channel>?>.value(),
      ) as _i3.Future<List<_i4.Channel>?>);
}
