// Mocks generated by Mockito 5.0.3 from annotations
// in hkgalden_flutter/test/bloc_tests/thread_list_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:hkgalden_flutter/models/thread.dart' as _i4;
import 'package:hkgalden_flutter/repository/thread_list_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ThreadListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockThreadListRepository extends _i1.Mock
    implements _i2.ThreadListRepository {
  MockThreadListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Thread>?> getThreadList(String? id, int? page) =>
      (super.noSuchMethod(Invocation.method(#getThreadList, [id, page]),
              returnValue: Future.value(<_i4.Thread>[]))
          as _i3.Future<List<_i4.Thread>?>);
}
